# Copyright 2023 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Kurp Modified'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["kurp"]'
      alphas: '["Colemak"]'
      custom_config: '["#define MIRYOKU_KLUDGE_BOTTOMROWCOMBOS\n#define MIRYOKU_KLUDGE_THUMBCOMBOS"]'
      kconfig: '["CONFIG_ZMK_COMBO_MAX_COMBOS_PER_KEY=16"]'
